# -*- coding: utf-8 -*-
"""88640.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w1grLVlEyRhl5dQfFCIoEFtz0PfXu1Vf
"""

def get_followers(n_followers, t_followers):
    giveaways = 0
    while n_followers < t_followers:
        n_followers += n_followers * 0.1
        giveaways += 1
    return giveaways

get_followers(100000,200000)